### ISSUE TITLE
Azure Sentinel Template: Guided Investigation - Process Alerts.ipynb - Buggy feature with Get List of Alerts widget

### ISSUE THREAD

**Issue by khangm** [Azure/Azure-Sentinel-Notebooks#118]
Under the section: Get List of Alerts --> Set query time boundaries, users need to select a time range.  Not any time range would work, especially the default one.  An error like below would be displayed.  The error did not give needed info to help users to understand the issue was with time range selection.  I intuitively guessed out it was related to the range selection by giving it different values.

MsticpyDataQueryError - we've hit an error while running

StatusDescription None
(err_code: None)
Query:
SecurityAlert | project-rename StartTimeUtc = StartTime, EndTimeUtc = EndTime, AlertDisplayName = DisplayName, Severity = AlertSeverity | extend AlertType = iif(isempty(AlertType), AlertName, AlertType) | where true | where TimeGenerated >= datetime(2021-10-26T10:14:13.361754Z) | where TimeGenerated <= datetime(2021-10-28T11:14:13.361754Z) | extend extendedProps = parse_json(ExtendedProperties) | extend CompromisedEntity = tostring(extendedProps["Compromised Host"]) | project-away extendedProps
;

For more help on fixing this error see:
Query failed

![image](https://user-images.githubusercontent.com/93353297/139345475-7894c771-44b5-4a41-ae96-2a34f3a2cbf0.png)

!![image](https://user-images.githubusercontent.com/93353297/139345305-f4888c50-d10e-4e01-a2e2-ed4fe762d0bb.png)

**Comment by ianhelle** [comment]
Thanks for reporting.
Yeah it's difficult to know how best to fix this since it is the query running in Log Analytics that's failing because it is trying to do some operations on no data.
I guess we could try a simple query for alerts prior to calling the main one.

**Comment by ianhelle** [comment]
Seems to be old issue in old notebook. No action/comments for > 1 year
