### ISSUE TITLE
Bad link in Wiki page

### ISSUE THREAD

**Issue by ktb-jcm** [Azure/Azure-Sentinel-Notebooks#123]
The Wiki page here:
        https://github.com/Azure/Azure-Sentinel-Notebooks/wiki/Can-I-install-MSTICPy-by-default-on-a-new-AML-compute

has a broken link for a shell script. Correct link is:
        https://github.com/Azure/Azure-Sentinel-Notebooks/blob/master/HowTos/aml-compute-setup.sh

**Comment by ianhelle** [comment]
@ktb-jcm Thanks. I've updated and included the script in the article

**Comment by ktb-jcm** [comment]
Thanks. Caught your webinar on Thursday, great stuff.
