### ISSUE TITLE
Script aml-compute-setup.sh does not install correct dependency for typing_extensions library

### ISSUE THREAD

**Issue by ktb-jcm** [Azure/Azure-Sentinel-Notebooks#124]
Creating a brand new AML compute instance and running the aml-compute-setup.sh script from this repository seems to successfully install msticpy.py
However, upon trying to import the library the following error is generated:

> Python 3.8.1 (default, Jan  8 2020, 22:29:32) 
> [GCC 7.3.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import msticpy
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msticpy/__init__.py", line 34, in <module>
>     from .nbtools.nbinit import init_notebook, current_providers
>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msticpy/nbtools/__init__.py", line 20, in <module>
>     from . import nbdisplay
>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msticpy/nbtools/nbdisplay.py", line 11, in <module>
>     from bokeh.io import output_notebook
>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/bokeh/io/__init__.py", line 24, in <module>
>     from .doc import curdoc
>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/bokeh/io/doc.py", line 29, in <module>
>     from .state import curstate
>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/bokeh/io/state.py", line 53, in <module>
>     from ..document import Document
>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/bokeh/document/__init__.py", line 50, in <module>
>     from .document import DEFAULT_TITLE ; DEFAULT_TITLE
>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/bokeh/document/document.py", line 56, in <module>
>     from ..core.json_encoder import serialize_json
>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/bokeh/core/json_encoder.py", line 75, in <module>
>     from ..util.serialization import (
>   File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/bokeh/util/serialization.py", line 51, in <module>
>     from typing_extensions import Literal, TypedDict, TypeGuard
> ImportError: cannot import name 'TypeGuard' from 'typing_extensions' (/anaconda/envs/azureml_py38/lib/python3.8/site-packages/typing_extensions.py)

Further inspection indicates the "TypeGuard" function isn't available in the version of installed typing_extensions library. Log of script output indicates typing_extensions-3.7.4.3 was to be installed, but a listing of current modules via pip shows typing-extensions-3.10.0.2

**Comment by ianhelle** [comment]
I think that this may have been an issue with Bokeh.
https://github.com/holoviz/panel/issues/2754
Seems you might have been unlucky enough to be trying this out with the published release having this bug in it.

**Comment by ktb-jcm** [comment]
I was able to re-create this just this week, working on our finalized Notebooks environment.

According to this page: https://docs.microsoft.com/en-us/azure/sentinel/notebook-get-started
if we get the message "**Runtime dependency of PyGObject is missing**" the solution is documented here: https://github.com/Azure/Azure-Sentinel-Notebooks/wiki/%22Runtime-dependency-of-PyGObject-is-missing%22-error

> !conda install --yes -c conda-forge pygobject

Ran that and it seemed to resolve the Pygobject issue, but then broke typing-extensions, which I fixed by upgrading:

> %pip install --upgrade typing-extensions

It seems to work right now? There's definitely some incongruousness still, may help to engage with the MSAL team and make sure they understand their upstream provider properly.

**Comment by ianhelle** [comment]
I'll fix the script to add this. 
I also have an update to the parts that install PyGObject and Libsecret.

**Comment by ianhelle** [comment]
A bit of background. 
Seems that Bokeh updated their code to use a class from typing extensions 3.10+ but never added this to their setup.py as a dependency. 
It works without this in Python 3.10 but not earlier Python versions that don't have version 3.10 of typing extensions installed.

**Comment by ianhelle** [comment]
From msticpy 2.0  typing-extensions 4.2 and greater is a requirement and will be installed with msticpy, if it isn't already there, so there should be no need for this in the compute setup script.
