### ISSUE TITLE
[SigmaRuleImporter.ipynb] Tables does not exist

### ISSUE THREAD

**Issue by jonyluke** [Azure/Azure-Sentinel-Notebooks#130]
Converted rules access tables that do not exist:

![imagen](https://user-images.githubusercontent.com/9436549/147261101-12ebc0c9-0d77-4c09-8fc4-cbdbf15642e3.png)

**Comment by ianhelle** [comment]
This is true. It would take a lot of time to map the sigma rule raw output onto the correct Sentinel tables and (in some cases) field names.
The converted rule will often need some manual editing before running.
