### ISSUE TITLE
Auth error for Credential Scan on Blob Storage notebook

### ISSUE THREAD

**Issue by klunghamer** [Azure/Azure-Sentinel-Notebooks#141]
Hello - 

I'm receiving the below error in the first cell of section 2 - Authentication to Azure Storage, after authenticating in the web browser:

"The public API of azure-cli-core has been deprecated starting 2.21.0, and this method can no longer return a valid credential. If you need to still use this method, you need to install 'azure-cli-core<2.21.0'. You may corrupt data if you use current CLI and old azure-cli-core. See also: https://aka.ms/azsdk/python/identity/migration"

Currently running the cells sequentially as suggested. Thanks.

**Comment by zhzhao8888** [comment]
It was due to version update on new AML CI, problem fixed.

**Comment by zhzhao8888** [comment]
Fixed
