### ISSUE TITLE
Getting issue in Get Started.ipynb while running Search a term Query

### ISSUE THREAD

**Issue by akn9050** [Azure/Azure-Sentinel-Notebooks#20]
Hi, 

In **Get Started.ipynb** notebook, following query is not working:
> scope to a table and a column
> %kql search in ({selected_table.value}) {selected_columns.value[0]}: '*local service' | take 5

Error: 
```
query execution error:
{
    "error": {
        "code": "BadArgumentError",
        "innererror": {
            "code": "SyntaxError",
            "innererror": {
                "code": "SYN0002",
                "line": 1,
                "message": "Query could not be parsed at '{' on line [1,11]",
                "pos": 11,
                "token": "{"
            },
            "message": "A recognition error occurred in the query."
        },
        "message": "The request had some invalid properties"
    }
}
```
Screenshot:
![Snag_f170c4e](https://user-images.githubusercontent.com/27498287/80000184-72ae8b80-84da-11ea-83c9-7bd986a1ca63.png)

**Comment by petebryan** [comment]
Hi @akn9050 the most common cause of these syntax errors is where the parameters we are passing in do not exist. 
Can you check that selected_table.value and selected_columns.value[0] have values assigned to them please.
 It appears that the selection widget for selected_columns has some issues in Azure Notebooks that might cause it not to return a valid value so I suspect that is the issue. I will work on a fix for this but if you could validate the above variable assignments that will help a lot. 
Thanks,
Pete

**Comment by akn9050** [comment]
@petebryan I verified this, selected_table.value and selected_columns.value[0] have the values assigned.

**Comment by petebryan** [comment]
Thanks @akn9050 I have created an updated version of this Notebook that I think should fix your issues. Can you give it a try for me please and let me know if you run into issues:
https://github.com/Azure/Azure-Sentinel-Notebooks/blob/getting-started-fix/Get%20Started.ipynb

**Comment by akn9050** [comment]
Hi @petebryan 
Thanks for the quick update :)
I will try the updated notebook and let you know by tomorrow.

**Comment by akn9050** [comment]
Hi @petebryan,

I have tested it again, but in Search a term cell getting the same error:

Please find the screenshot for your reference. 

![Snag_18499ccd](https://user-images.githubusercontent.com/27498287/80201415-b8d22f00-8641-11ea-999b-f5a13706ffb2.png)

**Comment by petebryan** [comment]
Hi @akn9050 thanks for the response.  From the screenshot it appears you are still running the original Notebook, can you please try the updated one under the getting-started-fix branch. You can find it here:
https://github.com/Azure/Azure-Sentinel-Notebooks/blob/getting-started-fix/Get%20Started.ipynb

**Comment by petebryan** [comment]
We've updated the Notebook.
However we are also deprecating this Notebook due to it being a bit out of date. We plan to work on a new Getting Started notebook in the near future.
