### ISSUE TITLE
"Adding Hunting Bookmarks" notebook not working

### ISSUE THREAD

**Issue by garybushey** [Azure/Azure-Sentinel-Notebooks#22]
In the "Adding Hunting Bookmarks" bookmark, in the 4th code pane, an error message is thrown every time it gets run.  The error is: 

AttributeError                            Traceback (most recent call last)
<ipython-input-4-74739c0a669f> in <module>
      1 # Retrieve access token
      2 creds, sub_id = get_azure_cli_credentials()
----> 3 token = creds._token_retriever()
      4 access_token = token[2]['accessToken']

AttributeError: '_CliCredentials' object has no attribute '_token_retriever'

**Comment by petebryan** [comment]
@zhzhao8888 I believe this is one of your notebooks.

**Comment by zhzhao8888** [comment]
It is due to the recent SDK update, fix is in PR.

**Comment by petebryan** [comment]
Thanks for the quick fix, I've merged your change.
